/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fisigym.vista;

/**
 *
 * @author bdlcc
 */
public class adminGestionGimnasios extends javax.swing.JFrame {

    /**
     * Creates new form adminGestionGimnasios
     */
    public adminGestionGimnasios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        elegirDistritoGym = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        elegirCiudadGym = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtNombreGym = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDirecciónGym = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtReferenciaGym = new javax.swing.JTextField();
        buttonServicios = new javax.swing.JButton();
        buttonVolverInicio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonGuardarGimnasio = new javax.swing.JButton();
        buttonCrearGimnasio = new javax.swing.JButton();
        buttonEditarGimnasio = new javax.swing.JButton();
        buttonEliminarGimnasio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaGimnasios = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        buttonBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarGymAdmin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 78, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Distrito:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        elegirDistritoGym.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(elegirDistritoGym, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 238, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ciudad:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        elegirCiudadGym.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad 1", "Ciudad 2", "Ciudad 3", "Ciudad 4" }));
        jPanel2.add(elegirCiudadGym, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 237, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel2.add(txtNombreGym, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 237, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));
        jPanel2.add(txtDirecciónGym, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 453, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Referencia:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));
        jPanel2.add(txtReferenciaGym, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 452, -1));

        buttonServicios.setBackground(new java.awt.Color(229, 136, 150));
        buttonServicios.setText("Servicios");
        jPanel2.add(buttonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 110, -1));

        buttonVolverInicio.setBackground(new java.awt.Color(237, 222, 224));
        buttonVolverInicio.setText("Volver");
        buttonVolverInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(buttonVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1110, 150));

        jPanel3.setBackground(new java.awt.Color(219, 217, 232));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGuardarGimnasio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/GuardarTodo.png"))); // NOI18N
        buttonGuardarGimnasio.setText("Grabar");
        buttonGuardarGimnasio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(buttonGuardarGimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        buttonCrearGimnasio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/nuevo.png"))); // NOI18N
        buttonCrearGimnasio.setText("Nuevo");
        buttonCrearGimnasio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(buttonCrearGimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        buttonEditarGimnasio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/Actualizar (2).png"))); // NOI18N
        buttonEditarGimnasio.setText("Editar");
        buttonEditarGimnasio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(buttonEditarGimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 100, -1));

        buttonEliminarGimnasio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/eliminar.png"))); // NOI18N
        buttonEliminarGimnasio.setText("Eliminar");
        buttonEliminarGimnasio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEliminarGimnasio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarGimnasioActionPerformed(evt);
            }
        });
        jPanel3.add(buttonEliminarGimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        TablaGimnasios.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), null));
        TablaGimnasios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Ciudad", "Distrito", "Dirección", "Referencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaGimnasios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaGimnasios);
        if (TablaGimnasios.getColumnModel().getColumnCount() > 0) {
            TablaGimnasios.getColumnModel().getColumn(0).setPreferredWidth(50);
            TablaGimnasios.getColumnModel().getColumn(1).setPreferredWidth(50);
            TablaGimnasios.getColumnModel().getColumn(2).setPreferredWidth(50);
            TablaGimnasios.getColumnModel().getColumn(3).setPreferredWidth(50);
            TablaGimnasios.getColumnModel().getColumn(4).setPreferredWidth(130);
            TablaGimnasios.getColumnModel().getColumn(5).setPreferredWidth(130);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1030, 320));

        jPanel4.setBackground(new java.awt.Color(248, 231, 248));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonBuscar.setText("Buscar");
        buttonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(buttonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel6.setText("Buscar ID:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel4.add(txtBuscarGymAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 359, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 570, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1090, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarGimnasioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarGimnasioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonEliminarGimnasioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminGestionGimnasios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminGestionGimnasios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminGestionGimnasios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminGestionGimnasios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminGestionGimnasios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaGimnasios;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCrearGimnasio;
    private javax.swing.JButton buttonEditarGimnasio;
    private javax.swing.JButton buttonEliminarGimnasio;
    private javax.swing.JButton buttonGuardarGimnasio;
    private javax.swing.JButton buttonServicios;
    private javax.swing.JButton buttonVolverInicio;
    private javax.swing.JComboBox<String> elegirCiudadGym;
    private javax.swing.JComboBox<String> elegirDistritoGym;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarGymAdmin;
    private javax.swing.JTextField txtDirecciónGym;
    private javax.swing.JTextField txtNombreGym;
    private javax.swing.JTextField txtReferenciaGym;
    // End of variables declaration//GEN-END:variables
}
