/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fisigym.vista;

/**
 *
 * @author bdlcc
 */
public class RegistrarAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarAdmin
     */
    public RegistrarAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombresAdmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidosAdmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoAdmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContraseñaAdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDNIAdmin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTeléfonoAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRucAdmin = new javax.swing.JTextField();
        buttonVolverRegistrarAdmin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistrarAdmin = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarRucAdmin = new javax.swing.JTextField();
        buscarRucAdmin = new javax.swing.JButton();
        buttonGuardarAdmin = new javax.swing.JButton();
        buttonNuevoAdmin = new javax.swing.JButton();
        buttonActualizarAdmin = new javax.swing.JButton();
        buttonEliminarAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 78, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel2.add(txtNombresAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 290, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel2.add(txtApellidosAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 290, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));
        jPanel2.add(txtCorreoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 300, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));
        jPanel2.add(txtContraseñaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 300, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel2.add(txtDNIAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 290, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teléfono:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));
        jPanel2.add(txtTeléfonoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 300, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ruc:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));
        jPanel2.add(txtRucAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 220, -1));

        buttonVolverRegistrarAdmin.setBackground(new java.awt.Color(204, 204, 255));
        buttonVolverRegistrarAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonVolverRegistrarAdmin.setText("Volver");
        jPanel2.add(buttonVolverRegistrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 160));

        jPanel3.setBackground(new java.awt.Color(219, 217, 232));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaRegistrarAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ruc", "DNI", "Nombres", "Apellidos", "Correo", "Contraseña", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRegistrarAdmin);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 920, 310));

        jPanel4.setBackground(new java.awt.Color(248, 231, 248));
        jPanel4.setPreferredSize(new java.awt.Dimension(570, 40));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("Buscar Ruc:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel4.add(txtBuscarRucAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 360, -1));

        buscarRucAdmin.setText("Buscar");
        jPanel4.add(buscarRucAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        buttonGuardarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/GuardarTodo.png"))); // NOI18N
        buttonGuardarAdmin.setText("Grabar");
        jPanel3.add(buttonGuardarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        buttonNuevoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/nuevo.png"))); // NOI18N
        buttonNuevoAdmin.setText("Nuevo");
        jPanel3.add(buttonNuevoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        buttonActualizarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/Actualizar (2).png"))); // NOI18N
        buttonActualizarAdmin.setText("Editar");
        jPanel3.add(buttonActualizarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        buttonEliminarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/eliminar.png"))); // NOI18N
        buttonEliminarAdmin.setText("Eliminar");
        jPanel3.add(buttonEliminarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1090, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarRucAdmin;
    private javax.swing.JButton buttonActualizarAdmin;
    private javax.swing.JButton buttonEliminarAdmin;
    private javax.swing.JButton buttonGuardarAdmin;
    private javax.swing.JButton buttonNuevoAdmin;
    private javax.swing.JButton buttonVolverRegistrarAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegistrarAdmin;
    private javax.swing.JTextField txtApellidosAdmin;
    private javax.swing.JTextField txtBuscarRucAdmin;
    private javax.swing.JTextField txtContraseñaAdmin;
    private javax.swing.JTextField txtCorreoAdmin;
    private javax.swing.JTextField txtDNIAdmin;
    private javax.swing.JTextField txtNombresAdmin;
    private javax.swing.JTextField txtRucAdmin;
    private javax.swing.JTextField txtTeléfonoAdmin;
    // End of variables declaration//GEN-END:variables
}
