/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fisigym.vista;

/**
 *
 * @author bdlcc
 */
public class SistemaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SistemaCliente
     */
    public SistemaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InicioAdmin = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        gimnasiosInicio = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        AdminPanel = new javax.swing.JTabbedPane();
        InicioPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        GestionMembresiasPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        elegirMembresía = new javax.swing.JComboBox<>();
        txtPrecioMembresia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        buttonActulizarMembresia = new javax.swing.JButton();
        GimnasiosPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonGimnasios = new javax.swing.JButton();
        buttonDistritos = new javax.swing.JButton();
        buttonCiudades = new javax.swing.JButton();
        buttonServicios = new javax.swing.JButton();
        talleresPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        registrarAdminPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        reportesPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        verClientesPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 78, 114));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/LogoAdmin.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(195, 95));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 18, -1, -1));

        InicioAdmin.setBackground(new java.awt.Color(189, 197, 200));
        InicioAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        InicioAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        InicioAdmin.setText("Inicio");
        InicioAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InicioAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        InicioAdmin.setIconTextGap(18);
        InicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioAdminActionPerformed(evt);
            }
        });
        jPanel1.add(InicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 113, 186, 34));

        jButton7.setBackground(new java.awt.Color(189, 197, 200));
        jButton7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        jButton7.setText("Gestionar membresías");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setIconTextGap(18);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 159, 186, 34));

        gimnasiosInicio.setBackground(new java.awt.Color(189, 197, 200));
        gimnasiosInicio.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        gimnasiosInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        gimnasiosInicio.setText("Gimnasios");
        gimnasiosInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gimnasiosInicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gimnasiosInicio.setIconTextGap(18);
        gimnasiosInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gimnasiosInicioActionPerformed(evt);
            }
        });
        jPanel1.add(gimnasiosInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 205, 186, 34));

        jButton9.setBackground(new java.awt.Color(189, 197, 200));
        jButton9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        jButton9.setText("Programar talleres");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.setIconTextGap(18);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 251, 186, 34));

        jButton10.setBackground(new java.awt.Color(189, 197, 200));
        jButton10.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        jButton10.setText("Registrar entrenador");
        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton10.setIconTextGap(18);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 297, 186, 34));

        jButton11.setBackground(new java.awt.Color(189, 197, 200));
        jButton11.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        jButton11.setText("Ver reportes");
        jButton11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton11.setIconTextGap(18);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 343, 186, 34));

        jButton12.setBackground(new java.awt.Color(189, 197, 200));
        jButton12.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        jButton12.setText("Ver clientes");
        jButton12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton12.setIconTextGap(18);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 389, 186, 34));

        jButton13.setBackground(new java.awt.Color(189, 197, 200));
        jButton13.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        jButton13.setText("Cerrar sesión");
        jButton13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton13.setIconTextGap(18);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 536, 186, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 590));

        AdminPanel.setBackground(new java.awt.Color(251, 251, 251));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel6.setText("Bienvenido!!!");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Usuario registrado : Administrador");

        jButton4.setText("Continuar");

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(InicioPanelLayout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jButton4))))
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel7)))
                .addContainerGap(465, Short.MAX_VALUE))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addGap(64, 64, 64)
                .addComponent(jLabel7)
                .addGap(87, 87, 87)
                .addComponent(jButton4)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        AdminPanel.addTab("Inicio", InicioPanel);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(61, 78, 114));
        jLabel12.setText("Membresías");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel13.setText("Membresía:");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel14.setText("Precio:");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel15.setText("Beneficios:");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        elegirMembresía.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        elegirMembresía.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diamante", "Zafiro", "Esmeralda" }));
        jPanel10.add(elegirMembresía, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 170, -1));

        txtPrecioMembresia.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jPanel10.add(txtPrecioMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 230, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("S/.");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 270, 110));

        jPanel11.setBackground(new java.awt.Color(200, 200, 234));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/DiamanteLogo.png"))); // NOI18N
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel29.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel29.setText("DIAMANTE");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel30.setText("ZAFIRO");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/Zafiro.png"))); // NOI18N
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel31.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel31.setText("ESMERALDA");
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/esmeralda.png"))); // NOI18N
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 470, 150));

        buttonBuscar.setText("Buscar");
        jPanel10.add(buttonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 80, -1));

        buttonActulizarMembresia.setBackground(new java.awt.Color(229, 136, 150));
        buttonActulizarMembresia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonActulizarMembresia.setForeground(new java.awt.Color(255, 255, 255));
        buttonActulizarMembresia.setText("Actualizar");
        jPanel10.add(buttonActulizarMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 100, -1));

        javax.swing.GroupLayout GestionMembresiasPanelLayout = new javax.swing.GroupLayout(GestionMembresiasPanel);
        GestionMembresiasPanel.setLayout(GestionMembresiasPanelLayout);
        GestionMembresiasPanelLayout.setHorizontalGroup(
            GestionMembresiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GestionMembresiasPanelLayout.setVerticalGroup(
            GestionMembresiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AdminPanel.addTab("Gestionar membresías", GestionMembresiasPanel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/MembresiaLogoCLien.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (28).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (29).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (30).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (31).png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        buttonGimnasios.setText("Gestionar Gimnasios");
        buttonGimnasios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGimnasiosActionPerformed(evt);
            }
        });
        jPanel2.add(buttonGimnasios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        buttonDistritos.setText("Gestionar Distritos");
        jPanel2.add(buttonDistritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        buttonCiudades.setText("Gestionar Ciudades");
        jPanel2.add(buttonCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        buttonServicios.setText("Gestionar Servicios");
        jPanel2.add(buttonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        javax.swing.GroupLayout GimnasiosPanelLayout = new javax.swing.GroupLayout(GimnasiosPanel);
        GimnasiosPanel.setLayout(GimnasiosPanelLayout);
        GimnasiosPanelLayout.setHorizontalGroup(
            GimnasiosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GimnasiosPanelLayout.setVerticalGroup(
            GimnasiosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GimnasiosPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminPanel.addTab("Gimnasios", GimnasiosPanel);

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel16.setText("Programacion de talleres");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setText("*Añadir nuevos talleres");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("* Ver informacion de talleres");

        jButton15.setText("Continuar");

        javax.swing.GroupLayout talleresPanelLayout = new javax.swing.GroupLayout(talleresPanel);
        talleresPanel.setLayout(talleresPanelLayout);
        talleresPanelLayout.setHorizontalGroup(
            talleresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(talleresPanelLayout.createSequentialGroup()
                .addGroup(talleresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(talleresPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel16))
                    .addGroup(talleresPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(talleresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)))
                    .addGroup(talleresPanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton15)))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        talleresPanelLayout.setVerticalGroup(
            talleresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(talleresPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel16)
                .addGap(66, 66, 66)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(94, 94, 94)
                .addComponent(jButton15)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        AdminPanel.addTab("Programar talleres", talleresPanel);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel19.setText("Registrar emntrenador");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText("* Cambiar opciones de entrenador");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setText("* Ver informacion de los entrenadores");

        jButton16.setText("Continuar");

        javax.swing.GroupLayout registrarAdminPanelLayout = new javax.swing.GroupLayout(registrarAdminPanel);
        registrarAdminPanel.setLayout(registrarAdminPanelLayout);
        registrarAdminPanelLayout.setHorizontalGroup(
            registrarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarAdminPanelLayout.createSequentialGroup()
                .addGroup(registrarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarAdminPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel19))
                    .addGroup(registrarAdminPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(registrarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)))
                    .addGroup(registrarAdminPanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton16)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        registrarAdminPanelLayout.setVerticalGroup(
            registrarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarAdminPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel19)
                .addGap(66, 66, 66)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(94, 94, 94)
                .addComponent(jButton16)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        AdminPanel.addTab("Registrar entrenador", registrarAdminPanel);

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel22.setText("Ver reportes");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setText("* Reporte de entrenadores");

        jButton17.setText("Continuar");

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel27.setText("* Reporte de sedes");

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel28.setText("* Reporte de disciplinas mas solicitadas");

        javax.swing.GroupLayout reportesPanelLayout = new javax.swing.GroupLayout(reportesPanel);
        reportesPanel.setLayout(reportesPanelLayout);
        reportesPanelLayout.setHorizontalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportesPanelLayout.createSequentialGroup()
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportesPanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton17))
                    .addGroup(reportesPanelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel22))
                    .addGroup(reportesPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel23)
                            .addComponent(jLabel28))))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        reportesPanelLayout.setVerticalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel22)
                .addGap(72, 72, 72)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(58, 58, 58)
                .addComponent(jButton17)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        AdminPanel.addTab("Ver reportes", reportesPanel);

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel25.setText("Ver clientes");

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel26.setText("* Ver informacion de clientes");

        jButton18.setText("Continuar");

        javax.swing.GroupLayout verClientesPanelLayout = new javax.swing.GroupLayout(verClientesPanel);
        verClientesPanel.setLayout(verClientesPanelLayout);
        verClientesPanelLayout.setHorizontalGroup(
            verClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verClientesPanelLayout.createSequentialGroup()
                .addGroup(verClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verClientesPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel26))
                    .addGroup(verClientesPanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton18))
                    .addGroup(verClientesPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel25)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        verClientesPanelLayout.setVerticalGroup(
            verClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verClientesPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel25)
                .addGap(65, 65, 65)
                .addComponent(jLabel26)
                .addGap(130, 130, 130)
                .addComponent(jButton18)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        AdminPanel.addTab("Ver clientes", verClientesPanel);

        getContentPane().add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 860, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioAdminActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void gimnasiosInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gimnasiosInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gimnasiosInicioActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void buttonGimnasiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGimnasiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGimnasiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminPanel;
    private javax.swing.JPanel GestionMembresiasPanel;
    private javax.swing.JPanel GimnasiosPanel;
    private javax.swing.JButton InicioAdmin;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JButton buttonActulizarMembresia;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCiudades;
    private javax.swing.JButton buttonDistritos;
    private javax.swing.JButton buttonGimnasios;
    private javax.swing.JButton buttonServicios;
    private javax.swing.JComboBox<String> elegirMembresía;
    private javax.swing.JButton gimnasiosInicio;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel registrarAdminPanel;
    private javax.swing.JPanel reportesPanel;
    private javax.swing.JPanel talleresPanel;
    private javax.swing.JTextField txtPrecioMembresia;
    private javax.swing.JPanel verClientesPanel;
    // End of variables declaration//GEN-END:variables
}
