/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fisigym.vista;

/**
 *
 * @author bdlcc
 */
public class SistemaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SistemaCliente
     */
    public SistemaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InicioAdmin = new javax.swing.JButton();
        GestionarMembresiasInicio = new javax.swing.JButton();
        gimnasiosInicioAdmin = new javax.swing.JButton();
        talleresInicioAdmin = new javax.swing.JButton();
        registrarAdmin = new javax.swing.JButton();
        verReportesInicioAdmin = new javax.swing.JButton();
        verClientesAdmin = new javax.swing.JButton();
        cerrarSesiónAdmin = new javax.swing.JButton();
        AdminPanel = new javax.swing.JTabbedPane();
        InicioPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        GimnasiosPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonGimnasios = new javax.swing.JButton();
        buttonDistritos = new javax.swing.JButton();
        buttonCiudades = new javax.swing.JButton();
        buttonServicios = new javax.swing.JButton();
        talleresPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        GestionMembresiasPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        elegirMembresía = new javax.swing.JComboBox<>();
        txtPrecioMembresia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        buttonActulizarMembresia = new javax.swing.JButton();
        registrarAdminPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCorreoAdmin = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        passwordAdmin = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        verClientesPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        reportesPanel = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 78, 114));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/LogoAdmin.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(195, 95));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 18, -1, -1));

        InicioAdmin.setBackground(new java.awt.Color(189, 197, 200));
        InicioAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        InicioAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        InicioAdmin.setText("Inicio");
        InicioAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InicioAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        InicioAdmin.setIconTextGap(18);
        InicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioAdminActionPerformed(evt);
            }
        });
        jPanel1.add(InicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 113, 186, 34));

        GestionarMembresiasInicio.setBackground(new java.awt.Color(189, 197, 200));
        GestionarMembresiasInicio.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        GestionarMembresiasInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        GestionarMembresiasInicio.setText("Gestionar membresías");
        GestionarMembresiasInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        GestionarMembresiasInicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        GestionarMembresiasInicio.setIconTextGap(18);
        GestionarMembresiasInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarMembresiasInicioActionPerformed(evt);
            }
        });
        jPanel1.add(GestionarMembresiasInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 159, 186, 34));

        gimnasiosInicioAdmin.setBackground(new java.awt.Color(189, 197, 200));
        gimnasiosInicioAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        gimnasiosInicioAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        gimnasiosInicioAdmin.setText("Gimnasios");
        gimnasiosInicioAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gimnasiosInicioAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gimnasiosInicioAdmin.setIconTextGap(18);
        gimnasiosInicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gimnasiosInicioAdminActionPerformed(evt);
            }
        });
        jPanel1.add(gimnasiosInicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 205, 186, 34));

        talleresInicioAdmin.setBackground(new java.awt.Color(189, 197, 200));
        talleresInicioAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        talleresInicioAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        talleresInicioAdmin.setText("Talleres");
        talleresInicioAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        talleresInicioAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        talleresInicioAdmin.setIconTextGap(18);
        talleresInicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talleresInicioAdminActionPerformed(evt);
            }
        });
        jPanel1.add(talleresInicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 251, 186, 34));

        registrarAdmin.setBackground(new java.awt.Color(189, 197, 200));
        registrarAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        registrarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        registrarAdmin.setText("Registrar administrador");
        registrarAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registrarAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        registrarAdmin.setIconTextGap(18);
        registrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAdminActionPerformed(evt);
            }
        });
        jPanel1.add(registrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 297, 186, 34));

        verReportesInicioAdmin.setBackground(new java.awt.Color(189, 197, 200));
        verReportesInicioAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        verReportesInicioAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        verReportesInicioAdmin.setText("Ver reportes");
        verReportesInicioAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        verReportesInicioAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        verReportesInicioAdmin.setIconTextGap(18);
        verReportesInicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReportesInicioAdminActionPerformed(evt);
            }
        });
        jPanel1.add(verReportesInicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 186, 34));

        verClientesAdmin.setBackground(new java.awt.Color(189, 197, 200));
        verClientesAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        verClientesAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        verClientesAdmin.setText("Clientes");
        verClientesAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        verClientesAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        verClientesAdmin.setIconTextGap(18);
        verClientesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClientesAdminActionPerformed(evt);
            }
        });
        jPanel1.add(verClientesAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 186, 34));

        cerrarSesiónAdmin.setBackground(new java.awt.Color(189, 197, 200));
        cerrarSesiónAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        cerrarSesiónAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioLogoCliente.png"))); // NOI18N
        cerrarSesiónAdmin.setText("Cerrar sesión");
        cerrarSesiónAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cerrarSesiónAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cerrarSesiónAdmin.setIconTextGap(18);
        cerrarSesiónAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesiónAdminActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarSesiónAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 536, 186, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 590));

        AdminPanel.setBackground(new java.awt.Color(251, 251, 251));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel6.setText("Bienvenido!!!");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Usuario registrado : Administrador");

        jButton4.setText("Continuar");

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(InicioPanelLayout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jButton4))))
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel7)))
                .addContainerGap(465, Short.MAX_VALUE))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addGap(64, 64, 64)
                .addComponent(jLabel7)
                .addGap(87, 87, 87)
                .addComponent(jButton4)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        AdminPanel.addTab("Inicio", InicioPanel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/MembresiaLogoCLien.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (28).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (29).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (30).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (31).png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        buttonGimnasios.setText("Gestionar Gimnasios");
        buttonGimnasios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGimnasiosActionPerformed(evt);
            }
        });
        jPanel2.add(buttonGimnasios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        buttonDistritos.setText("Gestionar Distritos");
        jPanel2.add(buttonDistritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        buttonCiudades.setText("Gestionar Ciudades");
        jPanel2.add(buttonCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        buttonServicios.setText("Gestionar Servicios");
        jPanel2.add(buttonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        javax.swing.GroupLayout GimnasiosPanelLayout = new javax.swing.GroupLayout(GimnasiosPanel);
        GimnasiosPanel.setLayout(GimnasiosPanelLayout);
        GimnasiosPanelLayout.setHorizontalGroup(
            GimnasiosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GimnasiosPanelLayout.setVerticalGroup(
            GimnasiosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GimnasiosPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminPanel.addTab("Gimnasios", GimnasiosPanel);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (33).png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (35).png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (34).png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (36).png"))); // NOI18N
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jButton1.setText("Gestionar Talleres");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jButton2.setText("Gestionar Entrenadores");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jButton3.setText("Gestionar Disciplinas");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        javax.swing.GroupLayout talleresPanelLayout = new javax.swing.GroupLayout(talleresPanel);
        talleresPanel.setLayout(talleresPanelLayout);
        talleresPanelLayout.setHorizontalGroup(
            talleresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        talleresPanelLayout.setVerticalGroup(
            talleresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(talleresPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminPanel.addTab("Programar talleres", talleresPanel);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(61, 78, 114));
        jLabel12.setText("Membresías");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel13.setText("Membresía:");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel14.setText("Precio:");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel15.setText("Beneficios:");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        elegirMembresía.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        elegirMembresía.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diamante", "Zafiro", "Esmeralda" }));
        jPanel10.add(elegirMembresía, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 170, -1));

        txtPrecioMembresia.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jPanel10.add(txtPrecioMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 230, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("S/.");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 270, 110));

        jPanel11.setBackground(new java.awt.Color(200, 200, 234));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/DiamanteLogo.png"))); // NOI18N
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel29.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel29.setText("DIAMANTE");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel30.setText("ZAFIRO");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/Zafiro.png"))); // NOI18N
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel31.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel31.setText("ESMERALDA");
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/esmeralda.png"))); // NOI18N
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 470, 150));

        buttonBuscar.setText("Buscar");
        jPanel10.add(buttonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 80, -1));

        buttonActulizarMembresia.setBackground(new java.awt.Color(229, 136, 150));
        buttonActulizarMembresia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonActulizarMembresia.setForeground(new java.awt.Color(255, 255, 255));
        buttonActulizarMembresia.setText("Actualizar");
        jPanel10.add(buttonActulizarMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 100, -1));

        javax.swing.GroupLayout GestionMembresiasPanelLayout = new javax.swing.GroupLayout(GestionMembresiasPanel);
        GestionMembresiasPanel.setLayout(GestionMembresiasPanelLayout);
        GestionMembresiasPanelLayout.setHorizontalGroup(
            GestionMembresiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GestionMembresiasPanelLayout.setVerticalGroup(
            GestionMembresiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AdminPanel.addTab("Gestionar membresías", GestionMembresiasPanel);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(61, 78, 114));
        jLabel19.setText("Ingrese sus credenciales");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel20.setText("Correo Electrónico");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        txtCorreoAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(txtCorreoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 500, -1));

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel21.setText("Contraseña");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        passwordAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(passwordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 500, -1));

        jButton5.setBackground(new java.awt.Color(229, 136, 150));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Acceder");
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        javax.swing.GroupLayout registrarAdminPanelLayout = new javax.swing.GroupLayout(registrarAdminPanel);
        registrarAdminPanel.setLayout(registrarAdminPanelLayout);
        registrarAdminPanelLayout.setHorizontalGroup(
            registrarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registrarAdminPanelLayout.setVerticalGroup(
            registrarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AdminPanel.addTab("Registrar administrador", registrarAdminPanel);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fisigym/imagenes/New Project (39).png"))); // NOI18N
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jButton6.setBackground(new java.awt.Color(229, 136, 150));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Gestionar Clientes");
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        javax.swing.GroupLayout verClientesPanelLayout = new javax.swing.GroupLayout(verClientesPanel);
        verClientesPanel.setLayout(verClientesPanelLayout);
        verClientesPanelLayout.setHorizontalGroup(
            verClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        verClientesPanelLayout.setVerticalGroup(
            verClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AdminPanel.addTab("Clientes", verClientesPanel);

        jButton17.setText("Continuar");

        javax.swing.GroupLayout reportesPanelLayout = new javax.swing.GroupLayout(reportesPanel);
        reportesPanel.setLayout(reportesPanelLayout);
        reportesPanelLayout.setHorizontalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportesPanelLayout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addGap(354, 354, 354))
        );
        reportesPanelLayout.setVerticalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportesPanelLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addGap(176, 176, 176))
        );

        AdminPanel.addTab("Ver reportes", reportesPanel);

        getContentPane().add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 860, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioAdminActionPerformed

    private void GestionarMembresiasInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarMembresiasInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionarMembresiasInicioActionPerformed

    private void gimnasiosInicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gimnasiosInicioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gimnasiosInicioAdminActionPerformed

    private void talleresInicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talleresInicioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talleresInicioAdminActionPerformed

    private void registrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarAdminActionPerformed

    private void verReportesInicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReportesInicioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verReportesInicioAdminActionPerformed

    private void verClientesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClientesAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verClientesAdminActionPerformed

    private void cerrarSesiónAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesiónAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesiónAdminActionPerformed

    private void buttonGimnasiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGimnasiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGimnasiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminPanel;
    private javax.swing.JPanel GestionMembresiasPanel;
    private javax.swing.JButton GestionarMembresiasInicio;
    private javax.swing.JPanel GimnasiosPanel;
    private javax.swing.JButton InicioAdmin;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JButton buttonActulizarMembresia;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCiudades;
    private javax.swing.JButton buttonDistritos;
    private javax.swing.JButton buttonGimnasios;
    private javax.swing.JButton buttonServicios;
    private javax.swing.JButton cerrarSesiónAdmin;
    private javax.swing.JComboBox<String> elegirMembresía;
    private javax.swing.JButton gimnasiosInicioAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField passwordAdmin;
    private javax.swing.JButton registrarAdmin;
    private javax.swing.JPanel registrarAdminPanel;
    private javax.swing.JPanel reportesPanel;
    private javax.swing.JButton talleresInicioAdmin;
    private javax.swing.JPanel talleresPanel;
    private javax.swing.JTextField txtCorreoAdmin;
    private javax.swing.JTextField txtPrecioMembresia;
    private javax.swing.JButton verClientesAdmin;
    private javax.swing.JPanel verClientesPanel;
    private javax.swing.JButton verReportesInicioAdmin;
    // End of variables declaration//GEN-END:variables
}
